package client

// ////////////////////////////////////////////////////////////////////////////////// //
//                                                                                    //
//                         Copyright (c) 2025 ESSENTIAL KAOS                          //
//      Apache License, Version 2.0 <https://www.apache.org/licenses/LICENSE-2.0>     //
//                                                                                    //
// ////////////////////////////////////////////////////////////////////////////////// //

import (
	"fmt"
	"strings"

	"github.com/essentialkaos/ek/v13/strutil"

	"github.com/essentialkaos/redy/v4"
)

// ////////////////////////////////////////////////////////////////////////////////// //

// CommandInfo is struct with info about command (name, params, support flag)
type CommandInfo struct {
	Name        string
	Params      []string
	IsSupported bool
}

// ////////////////////////////////////////////////////////////////////////////////// //

// commands is reversed slice with all available redis commands with required arguments
var commands []*CommandInfo

// ////////////////////////////////////////////////////////////////////////////////// //

// getCommands return slice with all available commands
func getCommands() []*CommandInfo {
	if commands == nil {
		commands = []*CommandInfo{
			{"ZUNIONSTORE", []string{"destination", "numkeys", "key…", "[WEIGHTS weight]…", "[AGGREGATE {SUM|MIN|MAX}]"}, false},
			{"ZUNION", []string{"numkeys", "key…", "[WEIGHTS weight]…", "[AGGREGATE {SUM|MIN|MAX}]", "[WITHSCORES]"}, false},
			{"ZSCORE", []string{"key", "member"}, false},
			{"ZSCAN", []string{"key", "cursor", "[MATCH pattern]", "[COUNT count]"}, false},
			{"ZREVRANK", []string{"key", "member", "[WITHSCORE]"}, false},
			{"ZREVRANGEBYSCORE", []string{"key", "max", "min", "[WITHSCORES]", "[LIMIT limit]"}, false},
			{"ZREVRANGEBYLEX", []string{"key", "max", "min", "[LIMIT limit]"}, false},
			{"ZREVRANGE", []string{"key", "start", "stop", "[WITHSCORES]"}, false},
			{"ZREMRANGEBYSCORE", []string{"key", "min", "max"}, false},
			{"ZREMRANGEBYRANK", []string{"key", "start", "stop"}, false},
			{"ZREMRANGEBYLEX", []string{"key", "min", "max"}, false},
			{"ZREM", []string{"key", "member…"}, false},
			{"ZRANK", []string{"key", "member", "[WITHSCORE]"}, false},
			{"ZRANGESTORE", []string{"dst", "src", "min", "max", "[{BYSCORE|BYLEX}]", "[REV]", "[LIMIT limit]"}, false},
			{"ZRANGEBYSCORE", []string{"key", "min", "max", "[WITHSCORES]", "[LIMIT limit]"}, false},
			{"ZRANGEBYLEX", []string{"key", "min", "max", "[LIMIT limit]"}, false},
			{"ZRANGE", []string{"key", "start", "stop", "[{BYSCORE|BYLEX}]", "[REV]", "[LIMIT limit]", "[WITHSCORES]"}, false},
			{"ZRANDMEMBER", []string{"key", "[options]"}, false},
			{"ZPOPMIN", []string{"key", "[count]"}, false},
			{"ZPOPMAX", []string{"key", "[count]"}, false},
			{"ZMSCORE", []string{"key", "member…"}, false},
			{"ZMPOP", []string{"numkeys", "key…", "{MIN|MAX}", "[COUNT count]"}, false},
			{"ZLEXCOUNT", []string{"key", "min", "max"}, false},
			{"ZINTERSTORE", []string{"destination", "numkeys", "key…", "[WEIGHTS weight]…", "[AGGREGATE {SUM|MIN|MAX}]"}, false},
			{"ZINTERCARD", []string{"numkeys", "key…", "[LIMIT limit]"}, false},
			{"ZINTER", []string{"numkeys", "key…", "[WEIGHTS weight]…", "[AGGREGATE {SUM|MIN|MAX}]", "[WITHSCORES]"}, false},
			{"ZINCRBY", []string{"key", "increment", "member"}, false},
			{"ZDIFFSTORE", []string{"destination", "numkeys", "key…"}, false},
			{"ZDIFF", []string{"numkeys", "key…", "[WITHSCORES]"}, false},
			{"ZCOUNT", []string{"key", "min", "max"}, false},
			{"ZCARD", []string{"key"}, false},
			{"ZADD", []string{"key", "[{NX|XX}]", "[{GT|LT}]", "[CH]", "[INCR]", "data…"}, false},
			{"XTRIM", []string{"key", "trim"}, false},
			{"XSETID", []string{"key", "last-id", "[ENTRIESADDED entries-added]", "[MAXDELETEDID max-deleted-id]"}, false},
			{"XREVRANGE", []string{"key", "end", "start", "[COUNT count]"}, false},
			{"XREADGROUP", []string{"GROUP group-block", "[COUNT count]", "[BLOCK milliseconds]", "[NOACK]", "STREAMS streams"}, false},
			{"XREAD", []string{"[COUNT count]", "[BLOCK milliseconds]", "STREAMS streams"}, false},
			{"XRANGE", []string{"key", "start", "end", "[COUNT count]"}, false},
			{"XPENDING", []string{"key", "group", "[filters]"}, false},
			{"XLEN", []string{"key"}, false},
			{"XINFO STREAM", []string{"key", "[full-block]"}, false},
			{"XINFO HELP", nil, false},
			{"XINFO GROUPS", []string{"key"}, false},
			{"XINFO CONSUMERS", []string{"key", "group"}, false},
			{"XINFO", nil, false},
			{"XGROUP SETID", []string{"key", "group", "{id|$}", "[ENTRIESREAD entries-read]"}, false},
			{"XGROUP HELP", nil, false},
			{"XGROUP DESTROY", []string{"key", "group"}, false},
			{"XGROUP DELCONSUMER", []string{"key", "group", "consumer"}, false},
			{"XGROUP CREATECONSUMER", []string{"key", "group", "consumer"}, false},
			{"XGROUP CREATE", []string{"key", "group", "{id|$}", "[MKSTREAM]", "[ENTRIESREAD entries-read]"}, false},
			{"XGROUP", nil, false},
			{"XDEL", []string{"key", "ID…"}, false},
			{"XCLAIM", []string{"key", "group", "consumer", "min-idle-time", "ID…", "[IDLE ms]", "[TIME unix-time-milliseconds]", "[RETRYCOUNT count]", "[FORCE]", "[JUSTID]", "[LASTID lastid]"}, false},
			{"XAUTOCLAIM", []string{"key", "group", "consumer", "min-idle-time", "start", "[COUNT count]", "[JUSTID]"}, false},
			{"XADD", []string{"key", "[NOMKSTREAM]", "[trim]", "{*|id}", "data…"}, false},
			{"XACK", []string{"key", "group", "ID…"}, false},
			{"WATCH", []string{"key…"}, false},
			{"WAITAOF", []string{"numlocal", "numreplicas", "timeout"}, false},
			{"WAIT", []string{"numreplicas", "timeout"}, false},
			{"UNWATCH", nil, false},
			{"UNSUBSCRIBE", []string{"[channel]…"}, false},
			{"UNLINK", []string{"key…"}, false},
			{"TYPE", []string{"key"}, false},
			{"TTL", []string{"key"}, false},
			{"TOUCH", []string{"key…"}, false},
			{"TIME", nil, false},
			{"SYNC", nil, false},
			{"SWAPDB", []string{"index1", "index2"}, false},
			{"SUNSUBSCRIBE", []string{"[shardchannel]…"}, false},
			{"SUNIONSTORE", []string{"destination", "key…"}, false},
			{"SUNION", []string{"key…"}, false},
			{"SUBSTR", []string{"key", "start", "end"}, false},
			{"SUBSCRIBE", []string{"channel…"}, false},
			{"STRLEN", []string{"key"}, false},
			{"SSUBSCRIBE", []string{"shardchannel…"}, false},
			{"SSCAN", []string{"key", "cursor", "[MATCH pattern]", "[COUNT count]"}, false},
			{"SREM", []string{"key", "member…"}, false},
			{"SRANDMEMBER", []string{"key", "[count]"}, false},
			{"SPUBLISH", []string{"shardchannel", "message"}, false},
			{"SPOP", []string{"key", "[count]"}, false},
			{"SORT_RO", []string{"key", "[BY pattern]", "[LIMIT limit]", "[GET pattern]…", "[{ASC|DESC}]", "[ALPHA]"}, false},
			{"SORT", []string{"key", "[BY pattern]", "[LIMIT limit]", "[GET pattern]…", "[{ASC|DESC}]", "[ALPHA]", "[STORE destination]"}, false},
			{"SMOVE", []string{"source", "destination", "member"}, false},
			{"SMISMEMBER", []string{"key", "member…"}, false},
			{"SMEMBERS", []string{"key"}, false},
			{"SLOWLOG RESET", nil, false},
			{"SLOWLOG LEN", nil, false},
			{"SLOWLOG HELP", nil, false},
			{"SLOWLOG GET", []string{"[count]"}, false},
			{"SLOWLOG", nil, false},
			{"SLAVEOF", []string{"{host-port|no-one}"}, false},
			{"SISMEMBER", []string{"key", "member"}, false},
			{"SINTERSTORE", []string{"destination", "key…"}, false},
			{"SINTERCARD", []string{"numkeys", "key…", "[LIMIT limit]"}, false},
			{"SINTER", []string{"key…"}, false},
			{"SHUTDOWN", []string{"[{NOSAVE|SAVE}]", "[NOW]", "[FORCE]", "[ABORT]"}, false},
			{"SETRANGE", []string{"key", "offset", "value"}, false},
			{"SETNX", []string{"key", "value"}, false},
			{"SETEX", []string{"key", "seconds", "value"}, false},
			{"SETBIT", []string{"key", "offset", "value"}, false},
			{"SET", []string{"key", "value", "[{NX|XX}]", "[GET]", "[{EX seconds|PX milliseconds|EXAT unix-time-seconds|PXAT unix-time-milliseconds|KEEPTTL}]"}, false},
			{"SENTINEL SLAVES", []string{"master-name"}, false},
			{"SENTINEL SIMULATE-FAILURE", []string{"[{crash-after-election|crash-after-promotion|help}]…"}, false},
			{"SENTINEL SET", []string{"master-name", "data…"}, false},
			{"SENTINEL SENTINELS", []string{"master-name"}, false},
			{"SENTINEL RESET", []string{"pattern"}, false},
			{"SENTINEL REPLICAS", []string{"master-name"}, false},
			{"SENTINEL REMOVE", []string{"master-name"}, false},
			{"SENTINEL PENDING-SCRIPTS", nil, false},
			{"SENTINEL MYID", nil, false},
			{"SENTINEL MONITOR", []string{"name", "ip", "port", "quorum"}, false},
			{"SENTINEL MASTERS", nil, false},
			{"SENTINEL MASTER", []string{"master-name"}, false},
			{"SENTINEL IS-MASTER-DOWN-BY-ADDR", []string{"ip", "port", "current-epoch", "runid"}, false},
			{"SENTINEL INFO-CACHE", []string{"nodename…"}, false},
			{"SENTINEL HELP", nil, false},
			{"SENTINEL GET-MASTER-ADDR-BY-NAME", []string{"master-name"}, false},
			{"SENTINEL FLUSHCONFIG", nil, false},
			{"SENTINEL FAILOVER", []string{"master-name"}, false},
			{"SENTINEL DEBUG", []string{"[data]…"}, false},
			{"SENTINEL CONFIG", []string{"{SET set…|GET parameter…}"}, false},
			{"SENTINEL CKQUORUM", []string{"master-name"}, false},
			{"SENTINEL", nil, false},
			{"SELECT", []string{"index"}, false},
			{"SDIFFSTORE", []string{"destination", "key…"}, false},
			{"SDIFF", []string{"key…"}, false},
			{"SCRIPT LOAD", []string{"script"}, false},
			{"SCRIPT KILL", nil, false},
			{"SCRIPT HELP", nil, false},
			{"SCRIPT FLUSH", []string{"[{ASYNC|SYNC}]"}, false},
			{"SCRIPT EXISTS", []string{"sha1…"}, false},
			{"SCRIPT DEBUG", []string{"{YES|SYNC|NO}"}, false},
			{"SCRIPT", nil, false},
			{"SCARD", []string{"key"}, false},
			{"SCAN", []string{"cursor", "[MATCH pattern]", "[COUNT count]", "[TYPE type]"}, false},
			{"SAVE", nil, false},
			{"SADD", []string{"key", "member…"}, false},
			{"RPUSHX", []string{"key", "element…"}, false},
			{"RPUSH", []string{"key", "element…"}, false},
			{"RPOPLPUSH", []string{"source", "destination"}, false},
			{"RPOP", []string{"key", "[count]"}, false},
			{"ROLE", nil, false},
			{"RESTORE-ASKING", []string{"key", "ttl", "serialized-value", "[REPLACE]", "[ABSTTL]", "[IDLETIME seconds]", "[FREQ frequency]"}, false},
			{"RESTORE", []string{"key", "ttl", "serialized-value", "[REPLACE]", "[ABSTTL]", "[IDLETIME seconds]", "[FREQ frequency]"}, false},
			{"RESET", nil, false},
			{"REPLICAOF", []string{"{host-port|no-one}"}, false},
			{"REPLCONF", nil, false},
			{"RENAMENX", []string{"key", "newkey"}, false},
			{"RENAME", []string{"key", "newkey"}, false},
			{"READWRITE", nil, false},
			{"READONLY", nil, false},
			{"RANDOMKEY", nil, false},
			{"QUIT", nil, false},
			{"PUNSUBSCRIBE", []string{"[pattern]…"}, false},
			{"PUBSUB SHARDNUMSUB", []string{"[shardchannel]…"}, false},
			{"PUBSUB SHARDCHANNELS", []string{"[pattern]"}, false},
			{"PUBSUB NUMSUB", []string{"[channel]…"}, false},
			{"PUBSUB NUMPAT", nil, false},
			{"PUBSUB HELP", nil, false},
			{"PUBSUB CHANNELS", []string{"[pattern]"}, false},
			{"PUBSUB", nil, false},
			{"PUBLISH", []string{"channel", "message"}, false},
			{"PTTL", []string{"key"}, false},
			{"PSYNC", []string{"replicationid", "offset"}, false},
			{"PSUBSCRIBE", []string{"pattern…"}, false},
			{"PSETEX", []string{"key", "milliseconds", "value"}, false},
			{"PING", []string{"[message]"}, false},
			{"PFSELFTEST", nil, false},
			{"PFMERGE", []string{"destkey", "[sourcekey]…"}, false},
			{"PFDEBUG", []string{"subcommand", "key"}, false},
			{"PFCOUNT", []string{"key…"}, false},
			{"PFADD", []string{"key", "[element]…"}, false},
			{"PEXPIRETIME", []string{"key"}, false},
			{"PEXPIREAT", []string{"key", "unix-time-milliseconds", "[{NX|XX|GT|LT}]"}, false},
			{"PEXPIRE", []string{"key", "milliseconds", "[{NX|XX|GT|LT}]"}, false},
			{"PERSIST", []string{"key"}, false},
			{"OBJECT REFCOUNT", []string{"key"}, false},
			{"OBJECT IDLETIME", []string{"key"}, false},
			{"OBJECT HELP", nil, false},
			{"OBJECT FREQ", []string{"key"}, false},
			{"OBJECT ENCODING", []string{"key"}, false},
			{"OBJECT", nil, false},
			{"MULTI", nil, false},
			{"MSETNX", []string{"data…"}, false},
			{"MSET", []string{"data…"}, false},
			{"MOVE", []string{"key", "db"}, false},
			{"MONITOR", nil, false},
			{"MODULE UNLOAD", []string{"name"}, false},
			{"MODULE LOADEX", []string{"path", "[CONFIG configs]…", "[ARGS args]…"}, false},
			{"MODULE LOAD", []string{"path", "[arg]…"}, false},
			{"MODULE LIST", nil, false},
			{"MODULE HELP", nil, false},
			{"MODULE", nil, false},
			{"MIGRATE", []string{"host", "port", "{key|\"\"}", "destination-db", "timeout", "[COPY]", "[REPLACE]", "[{AUTH password|AUTH2 auth2}]", "[KEYS key]…"}, false},
			{"MGET", []string{"key…"}, false},
			{"MEMORY USAGE", []string{"key", "[SAMPLES count]"}, false},
			{"MEMORY STATS", nil, false},
			{"MEMORY PURGE", nil, false},
			{"MEMORY MALLOC-STATS", nil, false},
			{"MEMORY HELP", nil, false},
			{"MEMORY DOCTOR", nil, false},
			{"MEMORY", nil, false},
			{"LTRIM", []string{"key", "start", "stop"}, false},
			{"LSET", []string{"key", "index", "element"}, false},
			{"LREM", []string{"key", "count", "element"}, false},
			{"LRANGE", []string{"key", "start", "stop"}, false},
			{"LPUSHX", []string{"key", "element…"}, false},
			{"LPUSH", []string{"key", "element…"}, false},
			{"LPOS", []string{"key", "element", "[RANK rank]", "[COUNT num-matches]", "[MAXLEN len]"}, false},
			{"LPOP", []string{"key", "[count]"}, false},
			{"LOLWUT", []string{"[VERSION version]"}, false},
			{"LMPOP", []string{"numkeys", "key…", "{LEFT|RIGHT}", "[COUNT count]"}, false},
			{"LMOVE", []string{"source", "destination", "{LEFT|RIGHT}", "{LEFT|RIGHT}"}, false},
			{"LLEN", []string{"key"}, false},
			{"LINSERT", []string{"key", "{BEFORE|AFTER}", "pivot", "element"}, false},
			{"LINDEX", []string{"key", "index"}, false},
			{"LCS", []string{"key1", "key2", "[LEN]", "[IDX]", "[MINMATCHLEN min-match-len]", "[WITHMATCHLEN]"}, false},
			{"LATENCY RESET", []string{"[event]…"}, false},
			{"LATENCY LATEST", nil, false},
			{"LATENCY HISTORY", []string{"event"}, false},
			{"LATENCY HISTOGRAM", []string{"[COMMAND]…"}, false},
			{"LATENCY HELP", nil, false},
			{"LATENCY GRAPH", []string{"event"}, false},
			{"LATENCY DOCTOR", nil, false},
			{"LATENCY", nil, false},
			{"LASTSAVE", nil, false},
			{"KEYS", []string{"pattern"}, false},
			{"INFO", []string{"[section]…"}, false},
			{"INCRBYFLOAT", []string{"key", "increment"}, false},
			{"INCRBY", []string{"key", "increment"}, false},
			{"INCR", []string{"key"}, false},
			{"HVALS", []string{"key"}, false},
			{"HTTL", []string{"key", "FIELDS fields"}, false},
			{"HSTRLEN", []string{"key", "field"}, false},
			{"HSETNX", []string{"key", "field", "value"}, false},
			{"HSET", []string{"key", "data…"}, false},
			{"HSCAN", []string{"key", "cursor", "[MATCH pattern]", "[COUNT count]", "[NOVALUES]"}, false},
			{"HRANDFIELD", []string{"key", "[options]"}, false},
			{"HPTTL", []string{"key", "FIELDS fields"}, false},
			{"HPEXPIRETIME", []string{"key", "FIELDS fields"}, false},
			{"HPEXPIREAT", []string{"key", "unix-time-milliseconds", "[{NX|XX|GT|LT}]", "FIELDS fields"}, false},
			{"HPEXPIRE", []string{"key", "milliseconds", "[{NX|XX|GT|LT}]", "FIELDS fields"}, false},
			{"HPERSIST", []string{"key", "FIELDS fields"}, false},
			{"HMSET", []string{"key", "data…"}, false},
			{"HMGET", []string{"key", "field…"}, false},
			{"HLEN", []string{"key"}, false},
			{"HKEYS", []string{"key"}, false},
			{"HINCRBYFLOAT", []string{"key", "field", "increment"}, false},
			{"HINCRBY", []string{"key", "field", "increment"}, false},
			{"HGETALL", []string{"key"}, false},
			{"HGET", []string{"key", "field"}, false},
			{"HEXPIRETIME", []string{"key", "FIELDS fields"}, false},
			{"HEXPIREAT", []string{"key", "unix-time-seconds", "[{NX|XX|GT|LT}]", "FIELDS fields"}, false},
			{"HEXPIRE", []string{"key", "seconds", "[{NX|XX|GT|LT}]", "FIELDS fields"}, false},
			{"HEXISTS", []string{"key", "field"}, false},
			{"HELLO", []string{"[arguments]"}, false},
			{"HDEL", []string{"key", "field…"}, false},
			{"GETSET", []string{"key", "value"}, false},
			{"GETRANGE", []string{"key", "start", "end"}, false},
			{"GETEX", []string{"key", "[{EX seconds|PX milliseconds|EXAT unix-time-seconds|PXAT unix-time-milliseconds|PERSIST}]"}, false},
			{"GETDEL", []string{"key"}, false},
			{"GETBIT", []string{"key", "offset"}, false},
			{"GET", []string{"key"}, false},
			{"GEOSEARCHSTORE", []string{"destination", "source", "{FROMMEMBER member|FROMLONLAT fromlonlat}", "{circle|box}", "[{ASC|DESC}]", "[count-block]", "[STOREDIST]"}, false},
			{"GEOSEARCH", []string{"key", "{FROMMEMBER member|FROMLONLAT fromlonlat}", "{circle|box}", "[{ASC|DESC}]", "[count-block]", "[WITHCOORD]", "[WITHDIST]", "[WITHHASH]"}, false},
			{"GEORADIUS_RO", []string{"key", "longitude", "latitude", "radius", "{m|km|ft|mi}", "[WITHCOORD]", "[WITHDIST]", "[WITHHASH]", "[count-block]", "[{ASC|DESC}]"}, false},
			{"GEORADIUSBYMEMBER_RO", []string{"key", "member", "radius", "{m|km|ft|mi}", "[WITHCOORD]", "[WITHDIST]", "[WITHHASH]", "[count-block]", "[{ASC|DESC}]"}, false},
			{"GEORADIUSBYMEMBER", []string{"key", "member", "radius", "{m|km|ft|mi}", "[WITHCOORD]", "[WITHDIST]", "[WITHHASH]", "[count-block]", "[{ASC|DESC}]", "[{STORE key|STOREDIST key}]"}, false},
			{"GEORADIUS", []string{"key", "longitude", "latitude", "radius", "{m|km|ft|mi}", "[WITHCOORD]", "[WITHDIST]", "[WITHHASH]", "[count-block]", "[{ASC|DESC}]", "[{STORE key|STOREDIST key}]"}, false},
			{"GEOPOS", []string{"key", "[member]…"}, false},
			{"GEOHASH", []string{"key", "[member]…"}, false},
			{"GEODIST", []string{"key", "member1", "member2", "[{m|km|ft|mi}]"}, false},
			{"GEOADD", []string{"key", "[{NX|XX}]", "[CH]", "data…"}, false},
			{"FUNCTION STATS", nil, false},
			{"FUNCTION RESTORE", []string{"serialized-value", "[{FLUSH|APPEND|REPLACE}]"}, false},
			{"FUNCTION LOAD", []string{"[REPLACE]", "function-code"}, false},
			{"FUNCTION LIST", []string{"[LIBRARYNAME library-name-pattern]", "[WITHCODE]"}, false},
			{"FUNCTION KILL", nil, false},
			{"FUNCTION HELP", nil, false},
			{"FUNCTION FLUSH", []string{"[{ASYNC|SYNC}]"}, false},
			{"FUNCTION DUMP", nil, false},
			{"FUNCTION DELETE", []string{"library-name"}, false},
			{"FUNCTION", nil, false},
			{"FLUSHDB", []string{"[{ASYNC|SYNC}]"}, false},
			{"FLUSHALL", []string{"[{ASYNC|SYNC}]"}, false},
			{"FCALL_RO", []string{"function", "numkeys", "[key]…", "[arg]…"}, false},
			{"FCALL", []string{"function", "numkeys", "[key]…", "[arg]…"}, false},
			{"FAILOVER", []string{"[TO target]", "[ABORT]", "[TIMEOUT milliseconds]"}, false},
			{"EXPIRETIME", []string{"key"}, false},
			{"EXPIREAT", []string{"key", "unix-time-seconds", "[{NX|XX|GT|LT}]"}, false},
			{"EXPIRE", []string{"key", "seconds", "[{NX|XX|GT|LT}]"}, false},
			{"EXISTS", []string{"key…"}, false},
			{"EXEC", nil, false},
			{"EVAL_RO", []string{"script", "numkeys", "[key]…", "[arg]…"}, false},
			{"EVALSHA_RO", []string{"sha1", "numkeys", "[key]…", "[arg]…"}, false},
			{"EVALSHA", []string{"sha1", "numkeys", "[key]…", "[arg]…"}, false},
			{"EVAL", []string{"script", "numkeys", "[key]…", "[arg]…"}, false},
			{"ECHO", []string{"message"}, false},
			{"DUMP", []string{"key"}, false},
			{"DISCARD", nil, false},
			{"DEL", []string{"key…"}, false},
			{"DECRBY", []string{"key", "decrement"}, false},
			{"DECR", []string{"key"}, false},
			{"DEBUG", nil, false},
			{"DBSIZE", nil, false},
			{"COPY", []string{"source", "destination", "[DB destination-db]", "[REPLACE]"}, false},
			{"CONFIG SET", []string{"data…"}, false},
			{"CONFIG REWRITE", nil, false},
			{"CONFIG RESETSTAT", nil, false},
			{"CONFIG HELP", nil, false},
			{"CONFIG GET", []string{"parameter…"}, false},
			{"CONFIG", nil, false},
			{"COMMAND LIST", []string{"[FILTERBY {MODULE module-name|ACLCAT category|PATTERN pattern}]"}, false},
			{"COMMAND INFO", []string{"[command-name]…"}, false},
			{"COMMAND HELP", nil, false},
			{"COMMAND GETKEYSANDFLAGS", []string{"command", "[arg]…"}, false},
			{"COMMAND GETKEYS", []string{"command", "[arg]…"}, false},
			{"COMMAND DOCS", []string{"[command-name]…"}, false},
			{"COMMAND COUNT", nil, false},
			{"COMMAND", nil, false},
			{"CLUSTER SLOTS", nil, false},
			{"CLUSTER SLAVES", []string{"node-id"}, false},
			{"CLUSTER SHARDS", nil, false},
			{"CLUSTER SETSLOT", []string{"slot", "{IMPORTING node-id|MIGRATING node-id|NODE node-id|STABLE}"}, false},
			{"CLUSTER SET-CONFIG-EPOCH", []string{"config-epoch"}, false},
			{"CLUSTER SAVECONFIG", nil, false},
			{"CLUSTER RESET", []string{"[{HARD|SOFT}]"}, false},
			{"CLUSTER REPLICATE", []string{"node-id"}, false},
			{"CLUSTER REPLICAS", []string{"node-id"}, false},
			{"CLUSTER NODES", nil, false},
			{"CLUSTER MYSHARDID", nil, false},
			{"CLUSTER MYID", nil, false},
			{"CLUSTER MEET", []string{"ip", "port", "[cluster-bus-port]"}, false},
			{"CLUSTER LINKS", nil, false},
			{"CLUSTER KEYSLOT", []string{"key"}, false},
			{"CLUSTER INFO", nil, false},
			{"CLUSTER HELP", nil, false},
			{"CLUSTER GETKEYSINSLOT", []string{"slot", "count"}, false},
			{"CLUSTER FORGET", []string{"node-id"}, false},
			{"CLUSTER FLUSHSLOTS", nil, false},
			{"CLUSTER FAILOVER", []string{"[{FORCE|TAKEOVER}]"}, false},
			{"CLUSTER DELSLOTSRANGE", []string{"range…"}, false},
			{"CLUSTER DELSLOTS", []string{"slot…"}, false},
			{"CLUSTER COUNTKEYSINSLOT", []string{"slot"}, false},
			{"CLUSTER COUNT-FAILURE-REPORTS", []string{"node-id"}, false},
			{"CLUSTER BUMPEPOCH", nil, false},
			{"CLUSTER ADDSLOTSRANGE", []string{"range…"}, false},
			{"CLUSTER ADDSLOTS", []string{"slot…"}, false},
			{"CLUSTER", nil, false},
			{"CLIENT UNPAUSE", nil, false},
			{"CLIENT UNBLOCK", []string{"client-id", "[{TIMEOUT|ERROR}]"}, false},
			{"CLIENT TRACKINGINFO", nil, false},
			{"CLIENT TRACKING", []string{"{ON|OFF}", "[REDIRECT client-id]", "[PREFIX prefix]…", "[BCAST]", "[OPTIN]", "[OPTOUT]", "[NOLOOP]"}, false},
			{"CLIENT SETNAME", []string{"connection-name"}, false},
			{"CLIENT SETINFO", []string{"{lib-name libname|lib-ver libver}"}, false},
			{"CLIENT REPLY", []string{"{ON|OFF|SKIP}"}, false},
			{"CLIENT PAUSE", []string{"timeout", "[{WRITE|ALL}]"}, false},
			{"CLIENT NO-TOUCH", []string{"{ON|OFF}"}, false},
			{"CLIENT NO-EVICT", []string{"{ON|OFF}"}, false},
			{"CLIENT LIST", []string{"[TYPE {normal|master|replica|pubsub}]", "[ID client-id]…"}, false},
			{"CLIENT KILL", []string{"{ip:port|{[ID client-id]|[TYPE {normal|master|slave|replica|pubsub}]|[USER username]|[ADDR ip:port]|[LADDR ip:port]|[SKIPME {YES|NO}]|[MAXAGE maxage]}…}"}, false},
			{"CLIENT INFO", nil, false},
			{"CLIENT ID", nil, false},
			{"CLIENT HELP", nil, false},
			{"CLIENT GETREDIR", nil, false},
			{"CLIENT GETNAME", nil, false},
			{"CLIENT CACHING", []string{"{YES|NO}"}, false},
			{"CLIENT", nil, false},
			{"BZPOPMIN", []string{"key…", "timeout"}, false},
			{"BZPOPMAX", []string{"key…", "timeout"}, false},
			{"BZMPOP", []string{"timeout", "numkeys", "key…", "{MIN|MAX}", "[COUNT count]"}, false},
			{"BRPOPLPUSH", []string{"source", "destination", "timeout"}, false},
			{"BRPOP", []string{"key…", "timeout"}, false},
			{"BLPOP", []string{"key…", "timeout"}, false},
			{"BLMPOP", []string{"timeout", "numkeys", "key…", "{LEFT|RIGHT}", "[COUNT count]"}, false},
			{"BLMOVE", []string{"source", "destination", "{LEFT|RIGHT}", "{LEFT|RIGHT}", "timeout"}, false},
			{"BITPOS", []string{"key", "bit", "[range]"}, false},
			{"BITOP", []string{"{AND|OR|XOR|NOT}", "destkey", "key…"}, false},
			{"BITFIELD_RO", []string{"key", "[GET get-block]…"}, false},
			{"BITFIELD", []string{"key", "[{GET get-block|write}]…"}, false},
			{"BITCOUNT", []string{"key", "[range]"}, false},
			{"BGSAVE", []string{"[SCHEDULE]"}, false},
			{"BGREWRITEAOF", nil, false},
			{"AUTH", []string{"[username]", "password"}, false},
			{"ASKING", nil, false},
			{"APPEND", []string{"key", "value"}, false},
			{"ACL WHOAMI", nil, false},
			{"ACL USERS", nil, false},
			{"ACL SETUSER", []string{"username", "[rule]…"}, false},
			{"ACL SAVE", nil, false},
			{"ACL LOG", []string{"[{count|RESET}]"}, false},
			{"ACL LOAD", nil, false},
			{"ACL LIST", nil, false},
			{"ACL HELP", nil, false},
			{"ACL GETUSER", []string{"username"}, false},
			{"ACL GENPASS", []string{"[bits]"}, false},
			{"ACL DRYRUN", []string{"username", "command", "[arg]…"}, false},
			{"ACL DELUSER", []string{"username…"}, false},
			{"ACL CAT", []string{"[category]"}, false},
			{"ACL", nil, false},
		}
	}

	return commands
}

// getAvailableCommands return slice with all server commands
func getAvailableCommands() []string {
	var result []string

	for _, command := range getCommands() {
		if command.IsSupported {
			result = append(result, command.Name)
		}
	}

	return result
}

// updateCommandsSupport update commands support by used server version
func updateCommandsSupport(client *redy.Client) error {
	resp := client.Cmd("COMMAND")

	if resp.Err != nil {
		return resp.Err
	}

	commandList, err := resp.Array()

	if err != nil {
		return fmt.Errorf("Can't decode commands info: %v", err)
	}

	for _, command := range commandList {
		commandInfo, err := command.List()

		if err != nil {
			return fmt.Errorf("Can't decode command info: %v", err)
		}

		if len(commandInfo) != 0 {
			for _, cmd := range getCommands() {
				if strutil.ReadField(cmd.Name, 0, false, ' ') == strings.ToUpper(commandInfo[0]) {
					cmd.IsSupported = true
				}
			}
		}
	}

	return nil
}
